# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe41a7444b6cccd80fc9f39e9cbfcdf2c119587c7b6120d9ab31aa43576c1e455d20a80a762d6cd75e2acaa51044da6a08b6f04dc38f56123f9716ec3421ce48

test:
  secret_key_base: 3c62ac61d40667b176d46b11c7ed05f6c69539c1219aec90f434c843c4ad94eb3e118776f21ebff36cb9b6836a7f786f2fa5631d0d4aa38a61e1796f5fe5d389

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
